require "3rd/init" -- 第三方插件
require "Common/init" -- Common模块的统一require
require "CommonExt/init" -- 项目组可拓展的Common模块的统一require
require "GameData/init" -- 客户端数据缓存中心
require "GameModule/init" -- 客户端玩法模块
require "GameNet/init" -- 玩法网络协议模块
--require "GameView/init" -- 客户端公共界面
require "Common/GamePlay/init" -- 玩法核心初始化
require "Logic/init" -- Logic模块的统一require
require "DataTable/init" -- 数据表